### ISSUE TITLE
[ENHANCEMENT]  Allow administrators to restrict which data reports may be extracted on a per-project basis.

### ISSUE THREAD

**Issue by remifrazierucsf** [susom/biocatalyst-link#1]
## Is your feature request related to a problem? Please describe.
The module currently permits all reports in a project to be extracted with the Biocatalyst link.  This can cause problems in environments where the Biocatalyst platform is permitted to contain less sensitive data than REDCap, where Biocatalyst users in the REDCap environment may have access to projects with reports that could contain sensitive data.

## Describe the solution you'd like
Update the module to include an option for administrators to restrict which data reports may be extracted on a per-project basis.

## Additional context

We have a strong need to be able to allow only specific reports to be pulled by the module.  The UCSF security environment has very strict rules on where PHI can live, and currently REDCap is cleared for PHI, but Biocatalyst will not be.  So we need to be able to ship only deid data across the Biocatalyst integration, which has created a requirement that our system admins review each activation of the module.  But we still can't restrict which reports a user can pull from a project, so it's very possible for someone to inadvertently pull out an identified report for consumption by Biocatalyst.

**Comment by yasukawa** [comment]
It looks like you are assuming the report_id will be, at most, 5 characters.  I think on larger systems, there may be report_ids larger than 99999.  Also, does the cast to varchar(5) work on your system?  On our system, I have to cast to char(5).

**Comment by remifrazierucsf** [comment]
@yasukawa thank you, this is a great catch.  Casting to varchar works for us but we're on MariaDB, not vanilla SQL.  There's absolutely no reason not to cast to something larger.  I'll update and push to my fork.

**Comment by remifrazierucsf** [comment]
@yasukawa made this correction with commit `350d3816e75250786e26ef9d7e250c40a0581aea`, which should appear in the PR now.

**Comment by remifrazierucsf** [comment]
See https://github.com/susom/biocatalyst-link/pull/2/commits/350d3816e75250786e26ef9d7e250c40a0581aea
