### ISSUE TITLE
[BUG] Report and report list SQL queries are not sanitized

### ISSUE THREAD

**Issue by remifrazierucsf** [susom/biocatalyst-link#5]
## Describe the bug
SQL queries called in the following functions are not sanitized to prevent SQL injection attack:

- `verifyReportAllowed()` (v0.3 and higher)
- `getProjectReports()` (v0.1 and higher)
- `getReportColumns()` (v0.1 and higher)
- `checkReportInProject()` (v0.1 and higher)

## Expected behavior
SQL injection protection should be applied to all parameterized queries.

## Additional context
From REDCap Framework v4 release notes:

 **Parameterized Queries** - Framework Version 4 requires that all `query()` method calls must include an additional `$parameters` argument.  All queries should be refactored so that all dynamic values are passed as parameters.  Please take a moment to read the [Query Documentation](../querying.md) page to get a feel for parameterized queries in general, then return here for the following specifics on transitioning modules to use them:
  - As of REDCap version v#.#.# (TDB in early 2020), the `query()` method supports (but does not require) the `$parameters` argument.  This allows module queries to be updated incrementally over time, prior to updating to Framework Version 4.
  - Parameters are automatically escaped, which means manual escaping methods like `db_escape()` and `db_real_escape_string()` should be removed to avoid double escaping.
  - Updating many queries will be as simple as replacing all variables in the SQL with question marks, then specifying those variables in the `$parameters` argument instead.  Cases that require additional handling are included below.
  - The `db_affected_rows()` method will no longer work.  See the [Query Documentation](../querying.md) page for an alternative.
  - Methods that begin with `mysqli_...` and operate on the MySQL result object will no longer work.  Please use the equivalent `db_...` methods instead.
  - Numeric column values will return as the `int` type in PHP where they previously returned as `string`.  This can cause problems for any type sensitive operations like triple equals checking.  The simplest solution to prevent potential issues without refactoring is to cast the numeric columns in either SQL or PHP.
    - In PHP you can cast all integer columns to strings manually, or by using the following utility method on each fetched row:
      - `$row = $module->convertIntsToStrings($row);`
    - In SQL you can cast values individually.  For example:
      - Before: `select project_id`
      - After: &nbsp;&nbsp;`select cast(project_id as char) as project_id`.
  - Queries using appended SQL strings can still use parameters.  For example:
    - Before: `$module->query("...where value like '{$value}%'");`
    - After: &nbsp;&nbsp;`$module->query("...where value like ?)", [$value . '%']");`
  - Please don't simply pass in an empty or partial parameter array while still manually appending parameters to your query string.  Using prepared statements with parameterized queries is important for security as described by [OWASP](https://cheatsheetseries.owasp.org/cheatsheets/SQL_Injection_Prevention_Cheat_Sheet.html) and security experts spanning many other development communities.
  - This may also be a good time replace any old `db_query()` calls as well.  Manually calling `db_query()` is deprecated in modules, and may be disallowed in the future.

**Comment by 123andy** [comment]
I'm sorry, @remifrazierucsf - but this issue is a little out of touch.

1) This module was released BEFORE version 4 of the framework and doesn't assert to be v4. 
2) The SQL generated in this module DOES prevent SQL injection.  If you are able to produce an actual vulnerability, please do share in private.

If you would like to refactor the code to be compliant with the suggested standards of the latest version of the framework, please make a pull request.

-A

**Comment by remifrazierucsf** [comment]
Got it - no problem - I was submitting the issue in preparation for an eventual PR, not as a statement about the original code.
________________________________
